/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "Java基础": {
      "key": "Java基础",
      "scope": "tags",
      "path": "/tags/Java基础/",
      "pageKeys": [
        "v-74e79daf"
      ]
    },
    "零基础": {
      "key": "零基础",
      "scope": "tags",
      "path": "/tags/零基础/",
      "pageKeys": [
        "v-74e79daf"
      ]
    },
    "Spring": {
      "key": "Spring",
      "scope": "tags",
      "path": "/tags/Spring/",
      "pageKeys": [
        "v-41df4dc8"
      ]
    },
    "SpringBoot": {
      "key": "SpringBoot",
      "scope": "tags",
      "path": "/tags/SpringBoot/",
      "pageKeys": [
        "v-41df4dc8"
      ]
    },
    "面向对象": {
      "key": "面向对象",
      "scope": "tags",
      "path": "/tags/面向对象/",
      "pageKeys": [
        "v-2a7af21c"
      ]
    },
    "JavaSE": {
      "key": "JavaSE",
      "scope": "tags",
      "path": "/tags/JavaSE/",
      "pageKeys": [
        "v-2a7af21c"
      ]
    },
    "vue": {
      "key": "vue",
      "scope": "tags",
      "path": "/tags/vue/",
      "pageKeys": [
        "v-c871b990"
      ]
    },
    "js": {
      "key": "js",
      "scope": "tags",
      "path": "/tags/js/",
      "pageKeys": [
        "v-c871b990"
      ]
    },
    "生活": {
      "key": "生活",
      "scope": "tags",
      "path": "/tags/生活/",
      "pageKeys": [
        "v-633e5308"
      ]
    },
    "分享生活": {
      "key": "分享生活",
      "scope": "tags",
      "path": "/tags/分享生活/",
      "pageKeys": [
        "v-633e5308"
      ]
    }
  },
  "categories": {
    "Java基础": {
      "key": "Java基础",
      "scope": "categories",
      "path": "/categories/Java基础/",
      "pageKeys": [
        "v-74e79daf"
      ]
    },
    "java": {
      "key": "java",
      "scope": "categories",
      "path": "/categories/java/",
      "pageKeys": [
        "v-41df4dc8",
        "v-2a7af21c"
      ]
    },
    "前端": {
      "key": "前端",
      "scope": "categories",
      "path": "/categories/前端/",
      "pageKeys": [
        "v-c871b990"
      ]
    },
    "生活": {
      "key": "生活",
      "scope": "categories",
      "path": "/categories/生活/",
      "pageKeys": [
        "v-633e5308"
      ]
    }
  },
  "timeline": {}
}